var first_name="Brayden";
var last_name="Le";
var a=8;
var b=12;
var full_name=first_name.concat(last_name);
console.log(full_name);
var add=a+b;
console.log(add);
var sub=a-b;
console.log(sub);
var mul=a*b;
console.log(mul);
var div=a/b;
console.log(div);
